[theme]
base = "light"
primaryColor = "#E30713"
backgroundColor = "#f5f6f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
